GET http://localhost:5000/api/vitapharm/home
Content-Type: application/json

###
POST http://localhost:5000/api/vitapharm/signup
Content-Type: application/json

{
    "email": "junior@gmail.com",
    "password": "Biggysmall@100!"
}

###
PATCH http://localhost:5000/api/vitapharm/products/1
Content-Type: application/json

{
    "field": "quantity",
    "value": 26
}