GET http://localhost:5000/api/vitapharm/home
Content-Type: application/json

###
POST http://localhost:5000/api/vitapharm/signup
Content-Type: application/json

{
    "email": "junior@gmail.com",
    "password": "Biggysmall@100!"
}

###
PATCH http://localhost:5000/api/vitapharm/products/1
Content-Type: application/json

{
    "field": "quantity",
    "value": 26
}

###
POST http://localhost:5000/api/vitapharm/products
Content-Type: application/json

{
  "name": "Product Name",
  "description": "Product Description",
  "category": "Category",
  "sub_category": "Subcategory",
  "brand": "Brand",
  "admin_id": 1,
  "variations": [
    {
      "size": "Small",
      "price": 10
    },
    {
      "size": "Medium",
      "price": 15
    },
    {
      "size": "Large",
      "price": 20
    }
  ]
}
