"""cartitem model update

Revision ID: 19c057589b0f
Revises: ec7ce8542bc0
Create Date: 2024-04-04 18:11:56.581822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19c057589b0f'
down_revision = 'ec7ce8542bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=128), nullable=True))
        batch_op.drop_constraint('cartitems_ibfk_1', type_='foreignkey')
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16277215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.LargeBinary(length=16277215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cartitems_ibfk_1', 'cart', ['cart_id'], ['id'])
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
