"""new model changes

Revision ID: 49f46922e3b3
Revises: 8213902a1878
Create Date: 2024-07-03 11:21:26.061750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49f46922e3b3'
down_revision = '8213902a1878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discountcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_type', sa.String(length=128), nullable=False))

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discount_code_applied', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discounted_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['payment_reference'])
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_token')
        batch_op.drop_column('discounted_total')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('discount_code_applied')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('original_total')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('appointment_type')

    op.drop_table('discountcodes')
    # ### end Alembic commands ###
