"""back_populates in models

Revision ID: 7171db22bd6b
Revises: 69865ee43833
Create Date: 2024-06-23 15:53:46.556484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7171db22bd6b'
down_revision = '69865ee43833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.MEDIUMBLOB(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
