"""relationship fixed in models

Revision ID: 8213902a1878
Revises: b04ba57fca96
Create Date: 2024-06-24 14:45:43.597851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8213902a1878'
down_revision = 'b04ba57fca96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.alter_column('variation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cartitems', ['cart_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_item_id')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.alter_column('variation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('price')

    # ### end Alembic commands ###
