"""added columns

Revision ID: 84d799472d01
Revises: b52b6496b340
Create Date: 2024-06-29 18:06:47.415589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84d799472d01'
down_revision = 'b52b6496b340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('discount_code', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))
        batch_op.alter_column('transaction_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['payment_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('transaction_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('discount_code')
        batch_op.drop_column('session_id')
        batch_op.drop_column('payment_reference')

    # ### end Alembic commands ###
