"""model changes to house mpesa

Revision ID: af2bc428bd56
Revises: 59899a7ca060
Create Date: 2024-06-23 21:23:55.497024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2bc428bd56'
down_revision = '59899a7ca060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customeremails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.drop_column('data')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliverycost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_column('variation_id', if_exists=True)
        batch_op.drop_column('product_variation_id', if_exists=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('status')
        batch_op.drop_column('total_price')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('deliverycost')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.MEDIUMBLOB(), nullable=True))
        batch_op.drop_column('url')

    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_variation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variation_id')

    op.drop_table('customeremails')
    # ### end Alembic commands ###
