"""added relationship to cartitems

Revision ID: b04ba57fca96
Revises: af2bc428bd56
Create Date: 2024-06-23 22:25:01.909383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04ba57fca96'
down_revision = 'af2bc428bd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_variations', ['variation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variation_id')

    # ### end Alembic commands ###
