"""model changes with backref

Revision ID: d5adc526b4bc
Revises: 18c2db25b26c
Create Date: 2024-06-24 13:50:19.182792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5adc526b4bc'
down_revision = '18c2db25b26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.alter_column('variation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.alter_column('variation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
