"""configured aws s3

Revision ID: dbb6c6bb9219
Revises: 763cb48b2e0a
Create Date: 2024-05-26 11:45:21.208775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbb6c6bb9219'
down_revision = '763cb48b2e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.MEDIUMBLOB(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
