"""variationsId for cartitems

Revision ID: e2d9ef744cd3
Revises: ff22ad0ff9db
Create Date: 2024-06-23 11:18:29.920727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2d9ef744cd3'
down_revision = 'ff22ad0ff9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [column['name'] for column in inspector.get_columns('cartitems')]

    if 'variation_id' not in columns:
        with op.batch_alter_table('cartitems') as batch_op:
            batch_op.add_column(sa.Column('variation_id', sa.Integer))

    # ### end Alembic commands ###


def downgrade():
    # Drop the 'variation_id' column added in upgrade()
    with op.batch_alter_table('cartitems') as batch_op:
        batch_op.drop_column('variation_id')

    # Ensure to drop the 'product_variation_id' column if it exists
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [column['name'] for column in inspector.get_columns('cartitems')]

    if 'product_variation_id' in columns:
        with op.batch_alter_table('cartitems') as batch_op:
            batch_op.drop_column('product_variation_id')



    # ### end Alembic commands ###
