"""changed imaged to blob datatype

Revision ID: f1538fa321ee
Revises: 528f2cf204be
Create Date: 2024-03-27 22:06:39.922550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1538fa321ee'
down_revision = '528f2cf204be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.MEDIUMBLOB(), nullable=True))

    # ### end Alembic commands ###
