"""removed session_id column on model

Revision ID: f8cf7e0f9e84
Revises: 84d799472d01
Create Date: 2024-06-29 20:11:56.940584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8cf7e0f9e84'
down_revision = '84d799472d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', mysql.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
