"""added product variation to cart item

Revision ID: ff22ad0ff9db
Revises: 5b20c15c64a7
Create Date: 2024-06-22 21:53:38.517243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff22ad0ff9db'
down_revision = '5b20c15c64a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_variation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_variations', ['product_variation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_variation_id')

    # ### end Alembic commands ###
